import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Navbar from "../(landing-page)/Navbar/Navbar";







const fout = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Contact",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
<div className="bg-black">
    <Navbar/>
    {children}
</div>
    );
}
